# Generated by Django 3.1.7 on 2021-03-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercici',
            name='sol_a',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='exercici',
            name='sol_b',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='exercici',
            name='sol_c',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='exercici',
            name='sol_d',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='exercici',
            name='sol_e',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
